{% set name = "idds-doma" %}
{% set version = "0.7.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/idds-doma-{{ version }}.tar.gz
  sha256: eb0ab5d1cde8b759ef06bbb4a6dbe6778f793afdaaae2c56be9fece9f7fc482d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - idds-common =={{ version }}
    - idds-workflow =={{ version }}
    - panda-client
    - python >=3.6

test:
  imports:
    - idds
    - idds.doma

about:
  home: https://pypi.org/project/idds-doma/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - yesw2000
